/// GENERATED CODE
/// This file is auto-generated by the 'scrape_icons' script, and should not be modified by hand.
/// See the README.md for more information.
/// Generated on Mon Apr 25 2022 21:34:27 GMT+0200 (Central European Summer Time)

import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:weather_icons/weather_icons.dart';

import 'util/test_widget.dart';

/// Shorthand function for testing the icon.
///
/// Used to save space in generated file.
_test(WidgetTester t, IconData icon) async {
  await t.pumpWidget(TestWidget(child: Icon(icon)));
  expect(find.byIcon(icon), findsOneWidget);
}

/// One test for each of the generated [WeatherIcon] data.
void main() {
  testWidgets('create WeatherIcons.day_sunny', (t) async {
    await _test(t, WeatherIcons.day_sunny);
  });

  testWidgets('create WeatherIcons.day_cloudy', (t) async {
    await _test(t, WeatherIcons.day_cloudy);
  });

  testWidgets('create WeatherIcons.day_cloudy_gusts', (t) async {
    await _test(t, WeatherIcons.day_cloudy_gusts);
  });

  testWidgets('create WeatherIcons.day_cloudy_windy', (t) async {
    await _test(t, WeatherIcons.day_cloudy_windy);
  });

  testWidgets('create WeatherIcons.day_fog', (t) async {
    await _test(t, WeatherIcons.day_fog);
  });

  testWidgets('create WeatherIcons.day_hail', (t) async {
    await _test(t, WeatherIcons.day_hail);
  });

  testWidgets('create WeatherIcons.day_haze', (t) async {
    await _test(t, WeatherIcons.day_haze);
  });

  testWidgets('create WeatherIcons.day_lightning', (t) async {
    await _test(t, WeatherIcons.day_lightning);
  });

  testWidgets('create WeatherIcons.day_rain', (t) async {
    await _test(t, WeatherIcons.day_rain);
  });

  testWidgets('create WeatherIcons.day_rain_mix', (t) async {
    await _test(t, WeatherIcons.day_rain_mix);
  });

  testWidgets('create WeatherIcons.day_rain_wind', (t) async {
    await _test(t, WeatherIcons.day_rain_wind);
  });

  testWidgets('create WeatherIcons.day_showers', (t) async {
    await _test(t, WeatherIcons.day_showers);
  });

  testWidgets('create WeatherIcons.day_sleet', (t) async {
    await _test(t, WeatherIcons.day_sleet);
  });

  testWidgets('create WeatherIcons.day_sleet_storm', (t) async {
    await _test(t, WeatherIcons.day_sleet_storm);
  });

  testWidgets('create WeatherIcons.day_snow', (t) async {
    await _test(t, WeatherIcons.day_snow);
  });

  testWidgets('create WeatherIcons.day_snow_thunderstorm', (t) async {
    await _test(t, WeatherIcons.day_snow_thunderstorm);
  });

  testWidgets('create WeatherIcons.day_snow_wind', (t) async {
    await _test(t, WeatherIcons.day_snow_wind);
  });

  testWidgets('create WeatherIcons.day_sprinkle', (t) async {
    await _test(t, WeatherIcons.day_sprinkle);
  });

  testWidgets('create WeatherIcons.day_storm_showers', (t) async {
    await _test(t, WeatherIcons.day_storm_showers);
  });

  testWidgets('create WeatherIcons.day_sunny_overcast', (t) async {
    await _test(t, WeatherIcons.day_sunny_overcast);
  });

  testWidgets('create WeatherIcons.day_thunderstorm', (t) async {
    await _test(t, WeatherIcons.day_thunderstorm);
  });

  testWidgets('create WeatherIcons.day_windy', (t) async {
    await _test(t, WeatherIcons.day_windy);
  });

  testWidgets('create WeatherIcons.solar_eclipse', (t) async {
    await _test(t, WeatherIcons.solar_eclipse);
  });

  testWidgets('create WeatherIcons.hot', (t) async {
    await _test(t, WeatherIcons.hot);
  });

  testWidgets('create WeatherIcons.day_cloudy_high', (t) async {
    await _test(t, WeatherIcons.day_cloudy_high);
  });

  testWidgets('create WeatherIcons.day_light_wind', (t) async {
    await _test(t, WeatherIcons.day_light_wind);
  });

  testWidgets('create WeatherIcons.night_clear', (t) async {
    await _test(t, WeatherIcons.night_clear);
  });

  testWidgets('create WeatherIcons.night_alt_cloudy', (t) async {
    await _test(t, WeatherIcons.night_alt_cloudy);
  });

  testWidgets('create WeatherIcons.night_alt_cloudy_gusts', (t) async {
    await _test(t, WeatherIcons.night_alt_cloudy_gusts);
  });

  testWidgets('create WeatherIcons.night_alt_cloudy_windy', (t) async {
    await _test(t, WeatherIcons.night_alt_cloudy_windy);
  });

  testWidgets('create WeatherIcons.night_alt_hail', (t) async {
    await _test(t, WeatherIcons.night_alt_hail);
  });

  testWidgets('create WeatherIcons.night_alt_lightning', (t) async {
    await _test(t, WeatherIcons.night_alt_lightning);
  });

  testWidgets('create WeatherIcons.night_alt_rain', (t) async {
    await _test(t, WeatherIcons.night_alt_rain);
  });

  testWidgets('create WeatherIcons.night_alt_rain_mix', (t) async {
    await _test(t, WeatherIcons.night_alt_rain_mix);
  });

  testWidgets('create WeatherIcons.night_alt_rain_wind', (t) async {
    await _test(t, WeatherIcons.night_alt_rain_wind);
  });

  testWidgets('create WeatherIcons.night_alt_showers', (t) async {
    await _test(t, WeatherIcons.night_alt_showers);
  });

  testWidgets('create WeatherIcons.night_alt_sleet', (t) async {
    await _test(t, WeatherIcons.night_alt_sleet);
  });

  testWidgets('create WeatherIcons.night_alt_sleet_storm', (t) async {
    await _test(t, WeatherIcons.night_alt_sleet_storm);
  });

  testWidgets('create WeatherIcons.night_alt_snow', (t) async {
    await _test(t, WeatherIcons.night_alt_snow);
  });

  testWidgets('create WeatherIcons.night_alt_snow_thunderstorm', (t) async {
    await _test(t, WeatherIcons.night_alt_snow_thunderstorm);
  });

  testWidgets('create WeatherIcons.night_alt_snow_wind', (t) async {
    await _test(t, WeatherIcons.night_alt_snow_wind);
  });

  testWidgets('create WeatherIcons.night_alt_sprinkle', (t) async {
    await _test(t, WeatherIcons.night_alt_sprinkle);
  });

  testWidgets('create WeatherIcons.night_alt_storm_showers', (t) async {
    await _test(t, WeatherIcons.night_alt_storm_showers);
  });

  testWidgets('create WeatherIcons.night_alt_thunderstorm', (t) async {
    await _test(t, WeatherIcons.night_alt_thunderstorm);
  });

  testWidgets('create WeatherIcons.night_cloudy', (t) async {
    await _test(t, WeatherIcons.night_cloudy);
  });

  testWidgets('create WeatherIcons.night_cloudy_gusts', (t) async {
    await _test(t, WeatherIcons.night_cloudy_gusts);
  });

  testWidgets('create WeatherIcons.night_cloudy_windy', (t) async {
    await _test(t, WeatherIcons.night_cloudy_windy);
  });

  testWidgets('create WeatherIcons.night_fog', (t) async {
    await _test(t, WeatherIcons.night_fog);
  });

  testWidgets('create WeatherIcons.night_hail', (t) async {
    await _test(t, WeatherIcons.night_hail);
  });

  testWidgets('create WeatherIcons.night_lightning', (t) async {
    await _test(t, WeatherIcons.night_lightning);
  });

  testWidgets('create WeatherIcons.night_partly_cloudy', (t) async {
    await _test(t, WeatherIcons.night_partly_cloudy);
  });

  testWidgets('create WeatherIcons.night_rain', (t) async {
    await _test(t, WeatherIcons.night_rain);
  });

  testWidgets('create WeatherIcons.night_rain_mix', (t) async {
    await _test(t, WeatherIcons.night_rain_mix);
  });

  testWidgets('create WeatherIcons.night_rain_wind', (t) async {
    await _test(t, WeatherIcons.night_rain_wind);
  });

  testWidgets('create WeatherIcons.night_showers', (t) async {
    await _test(t, WeatherIcons.night_showers);
  });

  testWidgets('create WeatherIcons.night_sleet', (t) async {
    await _test(t, WeatherIcons.night_sleet);
  });

  testWidgets('create WeatherIcons.night_sleet_storm', (t) async {
    await _test(t, WeatherIcons.night_sleet_storm);
  });

  testWidgets('create WeatherIcons.night_snow', (t) async {
    await _test(t, WeatherIcons.night_snow);
  });

  testWidgets('create WeatherIcons.night_snow_thunderstorm', (t) async {
    await _test(t, WeatherIcons.night_snow_thunderstorm);
  });

  testWidgets('create WeatherIcons.night_snow_wind', (t) async {
    await _test(t, WeatherIcons.night_snow_wind);
  });

  testWidgets('create WeatherIcons.night_sprinkle', (t) async {
    await _test(t, WeatherIcons.night_sprinkle);
  });

  testWidgets('create WeatherIcons.night_storm_showers', (t) async {
    await _test(t, WeatherIcons.night_storm_showers);
  });

  testWidgets('create WeatherIcons.night_thunderstorm', (t) async {
    await _test(t, WeatherIcons.night_thunderstorm);
  });

  testWidgets('create WeatherIcons.lunar_eclipse', (t) async {
    await _test(t, WeatherIcons.lunar_eclipse);
  });

  testWidgets('create WeatherIcons.stars', (t) async {
    await _test(t, WeatherIcons.stars);
  });

  testWidgets('create WeatherIcons.storm_showers', (t) async {
    await _test(t, WeatherIcons.storm_showers);
  });

  testWidgets('create WeatherIcons.thunderstorm', (t) async {
    await _test(t, WeatherIcons.thunderstorm);
  });

  testWidgets('create WeatherIcons.night_alt_cloudy_high', (t) async {
    await _test(t, WeatherIcons.night_alt_cloudy_high);
  });

  testWidgets('create WeatherIcons.night_cloudy_high', (t) async {
    await _test(t, WeatherIcons.night_cloudy_high);
  });

  testWidgets('create WeatherIcons.night_alt_partly_cloudy', (t) async {
    await _test(t, WeatherIcons.night_alt_partly_cloudy);
  });

  testWidgets('create WeatherIcons.cloud', (t) async {
    await _test(t, WeatherIcons.cloud);
  });

  testWidgets('create WeatherIcons.cloudy', (t) async {
    await _test(t, WeatherIcons.cloudy);
  });

  testWidgets('create WeatherIcons.cloudy_gusts', (t) async {
    await _test(t, WeatherIcons.cloudy_gusts);
  });

  testWidgets('create WeatherIcons.cloudy_windy', (t) async {
    await _test(t, WeatherIcons.cloudy_windy);
  });

  testWidgets('create WeatherIcons.fog', (t) async {
    await _test(t, WeatherIcons.fog);
  });

  testWidgets('create WeatherIcons.hail', (t) async {
    await _test(t, WeatherIcons.hail);
  });

  testWidgets('create WeatherIcons.rain', (t) async {
    await _test(t, WeatherIcons.rain);
  });

  testWidgets('create WeatherIcons.rain_mix', (t) async {
    await _test(t, WeatherIcons.rain_mix);
  });

  testWidgets('create WeatherIcons.rain_wind', (t) async {
    await _test(t, WeatherIcons.rain_wind);
  });

  testWidgets('create WeatherIcons.showers', (t) async {
    await _test(t, WeatherIcons.showers);
  });

  testWidgets('create WeatherIcons.sleet', (t) async {
    await _test(t, WeatherIcons.sleet);
  });

  testWidgets('create WeatherIcons.snow', (t) async {
    await _test(t, WeatherIcons.snow);
  });

  testWidgets('create WeatherIcons.sprinkle', (t) async {
    await _test(t, WeatherIcons.sprinkle);
  });

  testWidgets('create WeatherIcons.snow_wind', (t) async {
    await _test(t, WeatherIcons.snow_wind);
  });

  testWidgets('create WeatherIcons.smog', (t) async {
    await _test(t, WeatherIcons.smog);
  });

  testWidgets('create WeatherIcons.smoke', (t) async {
    await _test(t, WeatherIcons.smoke);
  });

  testWidgets('create WeatherIcons.lightning', (t) async {
    await _test(t, WeatherIcons.lightning);
  });

  testWidgets('create WeatherIcons.raindrops', (t) async {
    await _test(t, WeatherIcons.raindrops);
  });

  testWidgets('create WeatherIcons.raindrop', (t) async {
    await _test(t, WeatherIcons.raindrop);
  });

  testWidgets('create WeatherIcons.dust', (t) async {
    await _test(t, WeatherIcons.dust);
  });

  testWidgets('create WeatherIcons.snowflake_cold', (t) async {
    await _test(t, WeatherIcons.snowflake_cold);
  });

  testWidgets('create WeatherIcons.windy', (t) async {
    await _test(t, WeatherIcons.windy);
  });

  testWidgets('create WeatherIcons.strong_wind', (t) async {
    await _test(t, WeatherIcons.strong_wind);
  });

  testWidgets('create WeatherIcons.sandstorm', (t) async {
    await _test(t, WeatherIcons.sandstorm);
  });

  testWidgets('create WeatherIcons.earthquake', (t) async {
    await _test(t, WeatherIcons.earthquake);
  });

  testWidgets('create WeatherIcons.fire', (t) async {
    await _test(t, WeatherIcons.fire);
  });

  testWidgets('create WeatherIcons.flood', (t) async {
    await _test(t, WeatherIcons.flood);
  });

  testWidgets('create WeatherIcons.meteor', (t) async {
    await _test(t, WeatherIcons.meteor);
  });

  testWidgets('create WeatherIcons.tsunami', (t) async {
    await _test(t, WeatherIcons.tsunami);
  });

  testWidgets('create WeatherIcons.volcano', (t) async {
    await _test(t, WeatherIcons.volcano);
  });

  testWidgets('create WeatherIcons.hurricane', (t) async {
    await _test(t, WeatherIcons.hurricane);
  });

  testWidgets('create WeatherIcons.tornado', (t) async {
    await _test(t, WeatherIcons.tornado);
  });

  testWidgets('create WeatherIcons.small_craft_advisory', (t) async {
    await _test(t, WeatherIcons.small_craft_advisory);
  });

  testWidgets('create WeatherIcons.gale_warning', (t) async {
    await _test(t, WeatherIcons.gale_warning);
  });

  testWidgets('create WeatherIcons.storm_warning', (t) async {
    await _test(t, WeatherIcons.storm_warning);
  });

  testWidgets('create WeatherIcons.hurricane_warning', (t) async {
    await _test(t, WeatherIcons.hurricane_warning);
  });

  testWidgets('create WeatherIcons.wind_direction', (t) async {
    await _test(t, WeatherIcons.wind_direction);
  });

  testWidgets('create WeatherIcons.alien', (t) async {
    await _test(t, WeatherIcons.alien);
  });

  testWidgets('create WeatherIcons.celsius', (t) async {
    await _test(t, WeatherIcons.celsius);
  });

  testWidgets('create WeatherIcons.fahrenheit', (t) async {
    await _test(t, WeatherIcons.fahrenheit);
  });

  testWidgets('create WeatherIcons.degrees', (t) async {
    await _test(t, WeatherIcons.degrees);
  });

  testWidgets('create WeatherIcons.thermometer', (t) async {
    await _test(t, WeatherIcons.thermometer);
  });

  testWidgets('create WeatherIcons.thermometer_exterior', (t) async {
    await _test(t, WeatherIcons.thermometer_exterior);
  });

  testWidgets('create WeatherIcons.thermometer_internal', (t) async {
    await _test(t, WeatherIcons.thermometer_internal);
  });

  testWidgets('create WeatherIcons.cloud_down', (t) async {
    await _test(t, WeatherIcons.cloud_down);
  });

  testWidgets('create WeatherIcons.cloud_up', (t) async {
    await _test(t, WeatherIcons.cloud_up);
  });

  testWidgets('create WeatherIcons.cloud_refresh', (t) async {
    await _test(t, WeatherIcons.cloud_refresh);
  });

  testWidgets('create WeatherIcons.horizon', (t) async {
    await _test(t, WeatherIcons.horizon);
  });

  testWidgets('create WeatherIcons.horizon_alt', (t) async {
    await _test(t, WeatherIcons.horizon_alt);
  });

  testWidgets('create WeatherIcons.sunrise', (t) async {
    await _test(t, WeatherIcons.sunrise);
  });

  testWidgets('create WeatherIcons.sunset', (t) async {
    await _test(t, WeatherIcons.sunset);
  });

  testWidgets('create WeatherIcons.moonrise', (t) async {
    await _test(t, WeatherIcons.moonrise);
  });

  testWidgets('create WeatherIcons.moonset', (t) async {
    await _test(t, WeatherIcons.moonset);
  });

  testWidgets('create WeatherIcons.refresh', (t) async {
    await _test(t, WeatherIcons.refresh);
  });

  testWidgets('create WeatherIcons.refresh_alt', (t) async {
    await _test(t, WeatherIcons.refresh_alt);
  });

  testWidgets('create WeatherIcons.umbrella', (t) async {
    await _test(t, WeatherIcons.umbrella);
  });

  testWidgets('create WeatherIcons.barometer', (t) async {
    await _test(t, WeatherIcons.barometer);
  });

  testWidgets('create WeatherIcons.humidity', (t) async {
    await _test(t, WeatherIcons.humidity);
  });

  testWidgets('create WeatherIcons.na', (t) async {
    await _test(t, WeatherIcons.na);
  });

  testWidgets('create WeatherIcons.train', (t) async {
    await _test(t, WeatherIcons.train);
  });

  testWidgets('create WeatherIcons.moon_new', (t) async {
    await _test(t, WeatherIcons.moon_new);
  });

  testWidgets('create WeatherIcons.moon_waxing_crescent_1', (t) async {
    await _test(t, WeatherIcons.moon_waxing_crescent_1);
  });

  testWidgets('create WeatherIcons.moon_waxing_crescent_2', (t) async {
    await _test(t, WeatherIcons.moon_waxing_crescent_2);
  });

  testWidgets('create WeatherIcons.moon_waxing_crescent_3', (t) async {
    await _test(t, WeatherIcons.moon_waxing_crescent_3);
  });

  testWidgets('create WeatherIcons.moon_waxing_crescent_4', (t) async {
    await _test(t, WeatherIcons.moon_waxing_crescent_4);
  });

  testWidgets('create WeatherIcons.moon_waxing_crescent_5', (t) async {
    await _test(t, WeatherIcons.moon_waxing_crescent_5);
  });

  testWidgets('create WeatherIcons.moon_waxing_crescent_6', (t) async {
    await _test(t, WeatherIcons.moon_waxing_crescent_6);
  });

  testWidgets('create WeatherIcons.moon_first_quarter', (t) async {
    await _test(t, WeatherIcons.moon_first_quarter);
  });

  testWidgets('create WeatherIcons.moon_waxing_gibbous_1', (t) async {
    await _test(t, WeatherIcons.moon_waxing_gibbous_1);
  });

  testWidgets('create WeatherIcons.moon_waxing_gibbous_2', (t) async {
    await _test(t, WeatherIcons.moon_waxing_gibbous_2);
  });

  testWidgets('create WeatherIcons.moon_waxing_gibbous_3', (t) async {
    await _test(t, WeatherIcons.moon_waxing_gibbous_3);
  });

  testWidgets('create WeatherIcons.moon_waxing_gibbous_4', (t) async {
    await _test(t, WeatherIcons.moon_waxing_gibbous_4);
  });

  testWidgets('create WeatherIcons.moon_waxing_gibbous_5', (t) async {
    await _test(t, WeatherIcons.moon_waxing_gibbous_5);
  });

  testWidgets('create WeatherIcons.moon_waxing_gibbous_6', (t) async {
    await _test(t, WeatherIcons.moon_waxing_gibbous_6);
  });

  testWidgets('create WeatherIcons.moon_full', (t) async {
    await _test(t, WeatherIcons.moon_full);
  });

  testWidgets('create WeatherIcons.moon_waning_gibbous_1', (t) async {
    await _test(t, WeatherIcons.moon_waning_gibbous_1);
  });

  testWidgets('create WeatherIcons.moon_waning_gibbous_2', (t) async {
    await _test(t, WeatherIcons.moon_waning_gibbous_2);
  });

  testWidgets('create WeatherIcons.moon_waning_gibbous_3', (t) async {
    await _test(t, WeatherIcons.moon_waning_gibbous_3);
  });

  testWidgets('create WeatherIcons.moon_waning_gibbous_4', (t) async {
    await _test(t, WeatherIcons.moon_waning_gibbous_4);
  });

  testWidgets('create WeatherIcons.moon_waning_gibbous_5', (t) async {
    await _test(t, WeatherIcons.moon_waning_gibbous_5);
  });

  testWidgets('create WeatherIcons.moon_waning_gibbous_6', (t) async {
    await _test(t, WeatherIcons.moon_waning_gibbous_6);
  });

  testWidgets('create WeatherIcons.moon_third_quarter', (t) async {
    await _test(t, WeatherIcons.moon_third_quarter);
  });

  testWidgets('create WeatherIcons.moon_waning_crescent_1', (t) async {
    await _test(t, WeatherIcons.moon_waning_crescent_1);
  });

  testWidgets('create WeatherIcons.moon_waning_crescent_2', (t) async {
    await _test(t, WeatherIcons.moon_waning_crescent_2);
  });

  testWidgets('create WeatherIcons.moon_waning_crescent_3', (t) async {
    await _test(t, WeatherIcons.moon_waning_crescent_3);
  });

  testWidgets('create WeatherIcons.moon_waning_crescent_4', (t) async {
    await _test(t, WeatherIcons.moon_waning_crescent_4);
  });

  testWidgets('create WeatherIcons.moon_waning_crescent_5', (t) async {
    await _test(t, WeatherIcons.moon_waning_crescent_5);
  });

  testWidgets('create WeatherIcons.moon_waning_crescent_6', (t) async {
    await _test(t, WeatherIcons.moon_waning_crescent_6);
  });

  testWidgets('create WeatherIcons.moon_alt_new', (t) async {
    await _test(t, WeatherIcons.moon_alt_new);
  });

  testWidgets('create WeatherIcons.moon_alt_waxing_crescent_1', (t) async {
    await _test(t, WeatherIcons.moon_alt_waxing_crescent_1);
  });

  testWidgets('create WeatherIcons.moon_alt_waxing_crescent_2', (t) async {
    await _test(t, WeatherIcons.moon_alt_waxing_crescent_2);
  });

  testWidgets('create WeatherIcons.moon_alt_waxing_crescent_3', (t) async {
    await _test(t, WeatherIcons.moon_alt_waxing_crescent_3);
  });

  testWidgets('create WeatherIcons.moon_alt_waxing_crescent_4', (t) async {
    await _test(t, WeatherIcons.moon_alt_waxing_crescent_4);
  });

  testWidgets('create WeatherIcons.moon_alt_waxing_crescent_5', (t) async {
    await _test(t, WeatherIcons.moon_alt_waxing_crescent_5);
  });

  testWidgets('create WeatherIcons.moon_alt_waxing_crescent_6', (t) async {
    await _test(t, WeatherIcons.moon_alt_waxing_crescent_6);
  });

  testWidgets('create WeatherIcons.moon_alt_first_quarter', (t) async {
    await _test(t, WeatherIcons.moon_alt_first_quarter);
  });

  testWidgets('create WeatherIcons.moon_alt_waxing_gibbous_1', (t) async {
    await _test(t, WeatherIcons.moon_alt_waxing_gibbous_1);
  });

  testWidgets('create WeatherIcons.moon_alt_waxing_gibbous_2', (t) async {
    await _test(t, WeatherIcons.moon_alt_waxing_gibbous_2);
  });

  testWidgets('create WeatherIcons.moon_alt_waxing_gibbous_3', (t) async {
    await _test(t, WeatherIcons.moon_alt_waxing_gibbous_3);
  });

  testWidgets('create WeatherIcons.moon_alt_waxing_gibbous_4', (t) async {
    await _test(t, WeatherIcons.moon_alt_waxing_gibbous_4);
  });

  testWidgets('create WeatherIcons.moon_alt_waxing_gibbous_5', (t) async {
    await _test(t, WeatherIcons.moon_alt_waxing_gibbous_5);
  });

  testWidgets('create WeatherIcons.moon_alt_waxing_gibbous_6', (t) async {
    await _test(t, WeatherIcons.moon_alt_waxing_gibbous_6);
  });

  testWidgets('create WeatherIcons.moon_alt_full', (t) async {
    await _test(t, WeatherIcons.moon_alt_full);
  });

  testWidgets('create WeatherIcons.moon_alt_waning_gibbous_1', (t) async {
    await _test(t, WeatherIcons.moon_alt_waning_gibbous_1);
  });

  testWidgets('create WeatherIcons.moon_alt_waning_gibbous_2', (t) async {
    await _test(t, WeatherIcons.moon_alt_waning_gibbous_2);
  });

  testWidgets('create WeatherIcons.moon_alt_waning_gibbous_3', (t) async {
    await _test(t, WeatherIcons.moon_alt_waning_gibbous_3);
  });

  testWidgets('create WeatherIcons.moon_alt_waning_gibbous_4', (t) async {
    await _test(t, WeatherIcons.moon_alt_waning_gibbous_4);
  });

  testWidgets('create WeatherIcons.moon_alt_waning_gibbous_5', (t) async {
    await _test(t, WeatherIcons.moon_alt_waning_gibbous_5);
  });

  testWidgets('create WeatherIcons.moon_alt_waning_gibbous_6', (t) async {
    await _test(t, WeatherIcons.moon_alt_waning_gibbous_6);
  });

  testWidgets('create WeatherIcons.moon_alt_third_quarter', (t) async {
    await _test(t, WeatherIcons.moon_alt_third_quarter);
  });

  testWidgets('create WeatherIcons.moon_alt_waning_crescent_1', (t) async {
    await _test(t, WeatherIcons.moon_alt_waning_crescent_1);
  });

  testWidgets('create WeatherIcons.moon_alt_waning_crescent_2', (t) async {
    await _test(t, WeatherIcons.moon_alt_waning_crescent_2);
  });

  testWidgets('create WeatherIcons.moon_alt_waning_crescent_3', (t) async {
    await _test(t, WeatherIcons.moon_alt_waning_crescent_3);
  });

  testWidgets('create WeatherIcons.moon_alt_waning_crescent_4', (t) async {
    await _test(t, WeatherIcons.moon_alt_waning_crescent_4);
  });

  testWidgets('create WeatherIcons.moon_alt_waning_crescent_5', (t) async {
    await _test(t, WeatherIcons.moon_alt_waning_crescent_5);
  });

  testWidgets('create WeatherIcons.moon_alt_waning_crescent_6', (t) async {
    await _test(t, WeatherIcons.moon_alt_waning_crescent_6);
  });

  testWidgets('create WeatherIcons.time_1', (t) async {
    await _test(t, WeatherIcons.time_1);
  });

  testWidgets('create WeatherIcons.time_2', (t) async {
    await _test(t, WeatherIcons.time_2);
  });

  testWidgets('create WeatherIcons.time_3', (t) async {
    await _test(t, WeatherIcons.time_3);
  });

  testWidgets('create WeatherIcons.time_4', (t) async {
    await _test(t, WeatherIcons.time_4);
  });

  testWidgets('create WeatherIcons.time_5', (t) async {
    await _test(t, WeatherIcons.time_5);
  });

  testWidgets('create WeatherIcons.time_6', (t) async {
    await _test(t, WeatherIcons.time_6);
  });

  testWidgets('create WeatherIcons.time_7', (t) async {
    await _test(t, WeatherIcons.time_7);
  });

  testWidgets('create WeatherIcons.time_8', (t) async {
    await _test(t, WeatherIcons.time_8);
  });

  testWidgets('create WeatherIcons.time_9', (t) async {
    await _test(t, WeatherIcons.time_9);
  });

  testWidgets('create WeatherIcons.time_10', (t) async {
    await _test(t, WeatherIcons.time_10);
  });

  testWidgets('create WeatherIcons.time_11', (t) async {
    await _test(t, WeatherIcons.time_11);
  });

  testWidgets('create WeatherIcons.time_12', (t) async {
    await _test(t, WeatherIcons.time_12);
  });

  testWidgets('create WeatherIcons.direction_up', (t) async {
    await _test(t, WeatherIcons.direction_up);
  });

  testWidgets('create WeatherIcons.direction_up_right', (t) async {
    await _test(t, WeatherIcons.direction_up_right);
  });

  testWidgets('create WeatherIcons.direction_right', (t) async {
    await _test(t, WeatherIcons.direction_right);
  });

  testWidgets('create WeatherIcons.direction_down_right', (t) async {
    await _test(t, WeatherIcons.direction_down_right);
  });

  testWidgets('create WeatherIcons.direction_down', (t) async {
    await _test(t, WeatherIcons.direction_down);
  });

  testWidgets('create WeatherIcons.direction_down_left', (t) async {
    await _test(t, WeatherIcons.direction_down_left);
  });

  testWidgets('create WeatherIcons.direction_left', (t) async {
    await _test(t, WeatherIcons.direction_left);
  });

  testWidgets('create WeatherIcons.direction_up_left', (t) async {
    await _test(t, WeatherIcons.direction_up_left);
  });

  testWidgets('create WeatherIcons.towards_0_deg', (t) async {
    await _test(t, WeatherIcons.towards_0_deg);
  });

  testWidgets('create WeatherIcons.towards_23_deg', (t) async {
    await _test(t, WeatherIcons.towards_23_deg);
  });

  testWidgets('create WeatherIcons.towards_45_deg', (t) async {
    await _test(t, WeatherIcons.towards_45_deg);
  });

  testWidgets('create WeatherIcons.towards_68_deg', (t) async {
    await _test(t, WeatherIcons.towards_68_deg);
  });

  testWidgets('create WeatherIcons.towards_90_deg', (t) async {
    await _test(t, WeatherIcons.towards_90_deg);
  });

  testWidgets('create WeatherIcons.towards_113_deg', (t) async {
    await _test(t, WeatherIcons.towards_113_deg);
  });

  testWidgets('create WeatherIcons.towards_135_deg', (t) async {
    await _test(t, WeatherIcons.towards_135_deg);
  });

  testWidgets('create WeatherIcons.towards_158_deg', (t) async {
    await _test(t, WeatherIcons.towards_158_deg);
  });

  testWidgets('create WeatherIcons.towards_180_deg', (t) async {
    await _test(t, WeatherIcons.towards_180_deg);
  });

  testWidgets('create WeatherIcons.towards_203_deg', (t) async {
    await _test(t, WeatherIcons.towards_203_deg);
  });

  testWidgets('create WeatherIcons.towards_225_deg', (t) async {
    await _test(t, WeatherIcons.towards_225_deg);
  });

  testWidgets('create WeatherIcons.towards_248_deg', (t) async {
    await _test(t, WeatherIcons.towards_248_deg);
  });

  testWidgets('create WeatherIcons.towards_270_deg', (t) async {
    await _test(t, WeatherIcons.towards_270_deg);
  });

  testWidgets('create WeatherIcons.towards_293_deg', (t) async {
    await _test(t, WeatherIcons.towards_293_deg);
  });

  testWidgets('create WeatherIcons.towards_313_deg', (t) async {
    await _test(t, WeatherIcons.towards_313_deg);
  });

  testWidgets('create WeatherIcons.towards_336_deg', (t) async {
    await _test(t, WeatherIcons.towards_336_deg);
  });

  testWidgets('create WeatherIcons.from_180_deg', (t) async {
    await _test(t, WeatherIcons.from_180_deg);
  });

  testWidgets('create WeatherIcons.from_203_deg', (t) async {
    await _test(t, WeatherIcons.from_203_deg);
  });

  testWidgets('create WeatherIcons.from_225_deg', (t) async {
    await _test(t, WeatherIcons.from_225_deg);
  });

  testWidgets('create WeatherIcons.from_248_deg', (t) async {
    await _test(t, WeatherIcons.from_248_deg);
  });

  testWidgets('create WeatherIcons.from_270_deg', (t) async {
    await _test(t, WeatherIcons.from_270_deg);
  });

  testWidgets('create WeatherIcons.from_293_deg', (t) async {
    await _test(t, WeatherIcons.from_293_deg);
  });

  testWidgets('create WeatherIcons.from_313_deg', (t) async {
    await _test(t, WeatherIcons.from_313_deg);
  });

  testWidgets('create WeatherIcons.from_336_deg', (t) async {
    await _test(t, WeatherIcons.from_336_deg);
  });

  testWidgets('create WeatherIcons.from_0_deg', (t) async {
    await _test(t, WeatherIcons.from_0_deg);
  });

  testWidgets('create WeatherIcons.from_23_deg', (t) async {
    await _test(t, WeatherIcons.from_23_deg);
  });

  testWidgets('create WeatherIcons.from_45_deg', (t) async {
    await _test(t, WeatherIcons.from_45_deg);
  });

  testWidgets('create WeatherIcons.from_68_deg', (t) async {
    await _test(t, WeatherIcons.from_68_deg);
  });

  testWidgets('create WeatherIcons.from_90_deg', (t) async {
    await _test(t, WeatherIcons.from_90_deg);
  });

  testWidgets('create WeatherIcons.from_113_deg', (t) async {
    await _test(t, WeatherIcons.from_113_deg);
  });

  testWidgets('create WeatherIcons.from_135_deg', (t) async {
    await _test(t, WeatherIcons.from_135_deg);
  });

  testWidgets('create WeatherIcons.from_158_deg', (t) async {
    await _test(t, WeatherIcons.from_158_deg);
  });

  testWidgets('create WeatherIcons.towards_n', (t) async {
    await _test(t, WeatherIcons.towards_n);
  });

  testWidgets('create WeatherIcons.towards_nne', (t) async {
    await _test(t, WeatherIcons.towards_nne);
  });

  testWidgets('create WeatherIcons.towards_ne', (t) async {
    await _test(t, WeatherIcons.towards_ne);
  });

  testWidgets('create WeatherIcons.towards_ene', (t) async {
    await _test(t, WeatherIcons.towards_ene);
  });

  testWidgets('create WeatherIcons.towards_e', (t) async {
    await _test(t, WeatherIcons.towards_e);
  });

  testWidgets('create WeatherIcons.towards_ese', (t) async {
    await _test(t, WeatherIcons.towards_ese);
  });

  testWidgets('create WeatherIcons.towards_se', (t) async {
    await _test(t, WeatherIcons.towards_se);
  });

  testWidgets('create WeatherIcons.towards_sse', (t) async {
    await _test(t, WeatherIcons.towards_sse);
  });

  testWidgets('create WeatherIcons.towards_s', (t) async {
    await _test(t, WeatherIcons.towards_s);
  });

  testWidgets('create WeatherIcons.towards_ssw', (t) async {
    await _test(t, WeatherIcons.towards_ssw);
  });

  testWidgets('create WeatherIcons.towards_sw', (t) async {
    await _test(t, WeatherIcons.towards_sw);
  });

  testWidgets('create WeatherIcons.towards_wsw', (t) async {
    await _test(t, WeatherIcons.towards_wsw);
  });

  testWidgets('create WeatherIcons.towards_w', (t) async {
    await _test(t, WeatherIcons.towards_w);
  });

  testWidgets('create WeatherIcons.towards_wnw', (t) async {
    await _test(t, WeatherIcons.towards_wnw);
  });

  testWidgets('create WeatherIcons.towards_nw', (t) async {
    await _test(t, WeatherIcons.towards_nw);
  });

  testWidgets('create WeatherIcons.towards_nnw', (t) async {
    await _test(t, WeatherIcons.towards_nnw);
  });

  testWidgets('create WeatherIcons.from_n', (t) async {
    await _test(t, WeatherIcons.from_n);
  });

  testWidgets('create WeatherIcons.from_nne', (t) async {
    await _test(t, WeatherIcons.from_nne);
  });

  testWidgets('create WeatherIcons.from_ne', (t) async {
    await _test(t, WeatherIcons.from_ne);
  });

  testWidgets('create WeatherIcons.from_ene', (t) async {
    await _test(t, WeatherIcons.from_ene);
  });

  testWidgets('create WeatherIcons.from_e', (t) async {
    await _test(t, WeatherIcons.from_e);
  });

  testWidgets('create WeatherIcons.from_ese', (t) async {
    await _test(t, WeatherIcons.from_ese);
  });

  testWidgets('create WeatherIcons.from_se', (t) async {
    await _test(t, WeatherIcons.from_se);
  });

  testWidgets('create WeatherIcons.from_sse', (t) async {
    await _test(t, WeatherIcons.from_sse);
  });

  testWidgets('create WeatherIcons.from_s', (t) async {
    await _test(t, WeatherIcons.from_s);
  });

  testWidgets('create WeatherIcons.from_ssw', (t) async {
    await _test(t, WeatherIcons.from_ssw);
  });

  testWidgets('create WeatherIcons.from_sw', (t) async {
    await _test(t, WeatherIcons.from_sw);
  });

  testWidgets('create WeatherIcons.from_wsw', (t) async {
    await _test(t, WeatherIcons.from_wsw);
  });

  testWidgets('create WeatherIcons.from_w', (t) async {
    await _test(t, WeatherIcons.from_w);
  });

  testWidgets('create WeatherIcons.from_wnw', (t) async {
    await _test(t, WeatherIcons.from_wnw);
  });

  testWidgets('create WeatherIcons.from_nw', (t) async {
    await _test(t, WeatherIcons.from_nw);
  });

  testWidgets('create WeatherIcons.from_nnw', (t) async {
    await _test(t, WeatherIcons.from_nnw);
  });

  testWidgets('create WeatherIcons.wind_beaufort_0', (t) async {
    await _test(t, WeatherIcons.wind_beaufort_0);
  });

  testWidgets('create WeatherIcons.wind_beaufort_1', (t) async {
    await _test(t, WeatherIcons.wind_beaufort_1);
  });

  testWidgets('create WeatherIcons.wind_beaufort_2', (t) async {
    await _test(t, WeatherIcons.wind_beaufort_2);
  });

  testWidgets('create WeatherIcons.wind_beaufort_3', (t) async {
    await _test(t, WeatherIcons.wind_beaufort_3);
  });

  testWidgets('create WeatherIcons.wind_beaufort_4', (t) async {
    await _test(t, WeatherIcons.wind_beaufort_4);
  });

  testWidgets('create WeatherIcons.wind_beaufort_5', (t) async {
    await _test(t, WeatherIcons.wind_beaufort_5);
  });

  testWidgets('create WeatherIcons.wind_beaufort_6', (t) async {
    await _test(t, WeatherIcons.wind_beaufort_6);
  });

  testWidgets('create WeatherIcons.wind_beaufort_7', (t) async {
    await _test(t, WeatherIcons.wind_beaufort_7);
  });

  testWidgets('create WeatherIcons.wind_beaufort_8', (t) async {
    await _test(t, WeatherIcons.wind_beaufort_8);
  });

  testWidgets('create WeatherIcons.wind_beaufort_9', (t) async {
    await _test(t, WeatherIcons.wind_beaufort_9);
  });

  testWidgets('create WeatherIcons.wind_beaufort_10', (t) async {
    await _test(t, WeatherIcons.wind_beaufort_10);
  });

  testWidgets('create WeatherIcons.wind_beaufort_11', (t) async {
    await _test(t, WeatherIcons.wind_beaufort_11);
  });

  testWidgets('create WeatherIcons.wind_beaufort_12', (t) async {
    await _test(t, WeatherIcons.wind_beaufort_12);
  });

  testWidgets('create WeatherIcons.wind', (t) async {
    await _test(t, WeatherIcons.wind);
  });

  testWidgets('create WeatherIcons.wind_deg_0', (t) async {
    await _test(t, WeatherIcons.wind_deg_0);
  });

  testWidgets('create WeatherIcons.wind_deg_45', (t) async {
    await _test(t, WeatherIcons.wind_deg_45);
  });

  testWidgets('create WeatherIcons.wind_deg_90', (t) async {
    await _test(t, WeatherIcons.wind_deg_90);
  });

  testWidgets('create WeatherIcons.wind_deg_135', (t) async {
    await _test(t, WeatherIcons.wind_deg_135);
  });

  testWidgets('create WeatherIcons.wind_deg_180', (t) async {
    await _test(t, WeatherIcons.wind_deg_180);
  });

  testWidgets('create WeatherIcons.wind_deg_225', (t) async {
    await _test(t, WeatherIcons.wind_deg_225);
  });

  testWidgets('create WeatherIcons.wind_deg_270', (t) async {
    await _test(t, WeatherIcons.wind_deg_270);
  });

  testWidgets('create WeatherIcons.wind_deg_315', (t) async {
    await _test(t, WeatherIcons.wind_deg_315);
  });
}
